name: "ConfigMenu"
author: "Flowsqy"
version: "${project.version}"
main: "fr.flowsqy.configmenu.ConfigMenuPlugin"
api-version: "1.16"
depend:
  - DynamicCommand
  - AbstractMenu
commands:
  configmenureload:
    usage: /<command>
    description: "Reload all menu configurations"
    permission: "configmenu.command.reload"
    aliases:
      - cmrl
      - configmenurl
      - cmreload